POST /acr HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: test

{
  "action": "push",
  "id": "cb8c3971-9adc-488b-xxxx-43cbb4974ff5",
  "request": {
    "host": "test.azurecr.io",
    "id": "3cbb6949-7549-4fa1-xxxx-a6d5451dffc7",
    "method": "PUT",
    "useragent": "docker/17.09.0-ce go/go1.8.3 git-commit/afdb6d4 kernel/4.10.0-27-generic os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.0-ce \\(linux\\))"
  },
  "target": {
    "digest": "sha256:220611111e8c9bbe242e9dc1367c0fa89eef83f26203ee3f7c3764046e02b248",
    "length": 524,
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "repository": "nginx",
    "size": 524,
    "tag": "v1.1"
  },
  "timestamp": "2017-11-17T16:52:01.343145347Z"
}
