apiVersion: apps/v1
kind: Deployment
metadata:
  name: kobold
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kobold
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kobold
    spec:
      serviceAccountName: kobold
      imagePullSecrets: []
      securityContext:
        runAsNonRoot: true
        fsGroup: 2000
        runAsUser: 65532
        runAsGroup: 65532
      containers:
        - name: kobold
          image: index.docker.io/bluebrown/kobold:latest
          args:
            - --config=/etc/kobold/config.yaml
            - --watch
            - --k8schain
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: kobold-env
          env:
            - name: SERVICE_ACCOUNT_NAME
              value: kobold
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            failureThreshold: 1
            periodSeconds: 60
            httpGet:
              path: /livez
              port: http
          volumeMounts:
            - name: config
              mountPath: /etc/kobold
              readOnly: true
            - name: tmp
              mountPath: /tmp
              readOnly: false
      volumes:
        - name: config
          configMap:
            name: kobold-config
        - name: tmp
          emptyDir: {}
