kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kobold
nodes:
- role: control-plane

  # https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"

  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    protocol: TCP

  # https://github.com/containerd/containerd/blob/main/docs/hosts.md
  extraMounts:
  - hostPath: ./etc/containerd/certs.d
    containerPath: /etc/containerd/certs.d

containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
