[linters]
disable-all = true
enable = [
  "asasalint",
  "asciicheck",
  "bidichk",
  "bodyclose",
  "contextcheck",
  "dupword",
  "durationcheck",
  "errcheck",
  "errchkjson",
  # "exhaustive",
  "exportloopref",
  # "forbidigo",
  "gci",
  "gocheckcompilerdirectives",
  "gochecksumtype",
  "godot",
  # "godox",
  "gofmt",
  # "gomodguard",
  "gosec",
  "gosmopolitan",
  "makezero",
  "misspell",
  "musttag",
  "nilerr",
  "noctx",
  "perfsprint",
  "prealloc",
  "promlinter",
  "revive",
  "sloglint",
  "tenv",
  "thelper",
  "tparallel",
  # "typecheck",
]
