apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
sortOptions: {order: fifo}
labels: [{pairs: {feature: ingress-controller}}]
resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/kind/deploy.yaml
