apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels: [{pairs: {feature: container-registry}}]
sortOptions: {order: fifo}
resources:
- ./registry-config-cm.yaml
- ./registry-service.yaml
- ./registry-deploy.yaml
