apiVersion: apps/v1
kind: Deployment
metadata:
  name: distribution
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: distribution
  template:
    metadata:
      labels:
        app.kubernetes.io/name: distribution
    spec:
      containers:
      - name: distribution
        image: docker.io/library/registry:2
        resources: {}
        ports: [{containerPort: 5000}]
        readinessProbe: {tcpSocket: {port: 5000}}
        volumeMounts:
        - name: config
          mountPath: /etc/docker/registry/config.yml
          subPath: config.yml
          readOnly: true
        - name: data
          mountPath: /var/lib/registry
      volumes:
      - name: config
        configMap:
          name: distribution-config
          optional: true
      - name: data
        emptyDir: {}
