apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: myapp
      image: index.docker.io/bluebrown/busybox # kobold: tag: latest; type: exact
      resources: {}
