name: check
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'
        cache: false

    - name: install deps
      run: go mod download

    - name: run checks
      run: make check

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
        only-new-issues: true
        install-mode: "binary"
