name: check
on:
  workflow_dispatch: {}
  pull_request: {}
  push: {}
permissions:
  contents: read
  pull-requests: read
jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'
    - run: make .local/bin/sqlc .local/bin/swag
    - run: bash .github/diff.sh
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        only-new-issues: true
        install-mode: binary
