name: triage
on:
  issues:
    types:
    - opened
jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
    - run: gh issue edit $ISSUE_URL --add-label "triage"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_URL: ${{ github.event.issue.html_url }}
