apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-init
automountServiceAccountToken: true
imagePullSecrets: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-exec
rules:
- apiGroups: [""]
  resources: [pods/exec]
  verbs: [create]
- apiGroups: [""]
  resources: [pods]
  verbs: [get, list, watch]
- apiGroups: [apps]
  resources: [deployments]
  verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-init-pod-exec
  namespace: default
subjects:
- kind: ServiceAccount
  name: gitea-init
  namespace: default
roleRef:
  kind: Role
  name: pod-exec
  apiGroup: rbac.authorization.k8s.io
