apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels: [{pairs: {feature: git-server}}]
sortOptions: {order: fifo}
configMapGenerator:
- name: gitea-test-repo
  files:
  - ./testdata/repo.tar.gz
  options:
    disableNameSuffixHash: true
- name: gitea-init-scripts
  files:
  - ./testdata/init.sh
  options:
    disableNameSuffixHash: true
resources:
- ./gitea-deploy.yaml
- ./gitea-service.yaml
- ./init-rbac.yaml
- ./init-job.yaml
